name: Test workflow

on:
  push:
    branches:
      - master

jobs:
  test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: deployment test
        id: deploy_step
        run: echo "Deployment!"
      - name: error notification
        if: ${{ false }}
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo, message, commit, author, took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: deployment notification
        if: ${{ steps.deploy_step.conclusion === 'success' }}
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: commit, author, took
          custom_payload: |
            {
              attachments: [{
                color: 'good'
                text: `a new version deployed to https://some.url (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR} build took ${process.env.AS_TOOK}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}